### ISSUE TITLE
为什么当前 vscode 中的插件没有了「page」的概念？

### ISSUE THREAD

**Issue by tangdaohai** [appworks-lab/appworks#935]
### 问题描述/Problem Description

iceworks- cli 还有保留创建 page 物料的概念。

搭建的私有物料中，page 物料当前在 vscode 中已经找不到下载入口了。

**Comment by imsobear** [comment]
iceworks-cli 会移除 page 这个概念。如果对 page 有诉求，可以具体描述下，我们倾向于用 block 来满足。

**Comment by tangdaohai** [comment]
> iceworks-cli 会移除 page 这个概念。如果对 page 有诉求，可以具体描述下，我们倾向于用 block 来满足。

也不是什么特别的诉求。

移除 page 是因为官方团队认为 page 与 block 并无大的区别吗？

对于已存在私有物料中的 page 类物料，官方建议如何处理？
@imsobear

**Comment by miniGean** [comment]
> iceworks-cli 会移除 page 这个概念。如果对 page 有诉求，可以具体描述下，我们倾向于用 block 来满足。

目前使用block来组件页面时，无法控制布局，也无法

> iceworks-cli 会移除 page 这个概念。如果对 page 有诉求，可以具体描述下，我们倾向于用 block 来满足。

目前使用block组件页面时，需要引入之后再去调整布局，且无法处理组件间的事件回调等深层次的关联关系，使用page的话能够弥补block的这些不足。

**Comment by miniGean** [comment]
> iceworks-cli 会移除 page 这个概念。如果对 page 有诉求，可以具体描述下，我们倾向于用 block 来满足。

目前使用block来组件页面时，无法控制布局，也无法

> iceworks-cli 会移除 page 这个概念。如果对 page 有诉求，可以具体描述下，我们倾向于用 block 来满足。

目前使用block组件页面时，需要引入之后再去调整布局，且无法处理组件间的事件回调等深层次的关联关系，使用page的话能够弥补block的这些不足。

**Comment by imsobear** [comment]
> > iceworks-cli 会移除 page 这个概念。如果对 page 有诉求，可以具体描述下，我们倾向于用 block 来满足。
> 
> 也不是什么特别的诉求。
> 
> 移除 page 是因为官方团队认为 page 与 block 并无大的区别吗？
> 
> 对于已存在私有物料中的 page 类物料，官方建议如何处理？
> @imsobear

是的，区别很少，不想再加一个概念，如果对 block 有新的诉求欢迎反馈，现有 page 建议迁移到 block，迁移过程中有能力不满足之类的可以反馈给我们。

**Comment by tangdaohai** [comment]
谢谢。
现在只不过感觉将 page 迁移为 block 是个苦力活...
